<?php
/**
 * crpCasa
 *
 * @copyright (c) 2009 Daniele Conca
 * @link http://code.zikula.org/crpcasa Support and documentation
 * @author Daniele Conca <conca.daniele@gmail.com>
 * @license GNU/LGPL - v.3
 * @package crpCasa
 */


Loader :: includeOnce('modules/crpCasa/pnclass/crpCasa.php');

/**
 * the main administration function
 *
 * @return string HTML output
 */
function crpCasa_admin_main()
{
	// Security check
	if (!SecurityUtil :: checkPermission('crpCasa::', '::', ACCESS_EDIT))
	{
		return LogUtil :: registerPermissionError();
	}

	// Create output object
	$pnRender = new pnRender('crpCasa', false);

	// Return the output that has been generated by this function
	return $pnRender->fetch('crpcasa_admin_main.htm');
}



/**
 * modify module configuration
 *
 * @return string HTML output string
 */
function crpCasa_admin_modifyconfig()
{
	// Security check
	if (!SecurityUtil :: checkPermission('crpCasa::', '::', ACCESS_EDIT))
	{
		return LogUtil :: registerPermissionError();
	}

	$crpcasa = new crpCasa();
	return $crpcasa->modifyConfig();
}

/**
 * modify module configuration
 *
 * @return string HTML output string
 */
function crpCasa_admin_updateconfig()
{
  // Security check
  if (!SecurityUtil::checkPermission('crpCasa::', '::', ACCESS_EDIT)) {
      return LogUtil::registerPermissionError();
  }

  $crpcasa = new crpCasa();
	return $crpcasa->updateConfig();
}